version: 2

updates:
  - directory: /
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/New_York
    reviewers:
      - i-am-gizm0
